profile: cover.short.profile,cover.long.profile
local-prefix: "github.com/Joaquimborges/corvo"

threshold:
  file: 92
  package: 80
  total: 95

override:
  - threshold: 85
    path: client.go$
#exclude:
#paths:
#  - main.go$
