name: Coverage Check

on:
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: generate test coverage
        run: make test

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/.testcoverage.yml
